export default [
    {
        chapter: 1,
        name: "",
        statements: [
            {
                id: "1",
                type: "definition",
                content: "Let $X$ be a set. A collection $\\mathcal{T}\\subseteq\\mathcal{P}(X)$ is called a topology on $X$ if $\\mathcal{T}$ satisfies the following properties $\\\\ \\text{1. }$ $\\varnothing\\in\\mathcal{T}$ and $X\\in\\mathcal{T}.$ $\\\\ \\text{2. }$ $\\mathcal{T}$ is closed under finite intersections. That is, given an",
                short: "A collection $\\mathcal{T}\\subseteq\\mathcal{P}(X)$ is called a topology on $X$ if it contains $\\varnothing$ and $X$, and is closed under unions and finite intersections.",
                depending: []
            },
            {
                id: "2",
                type: "definition",
                content: "",
                short: "A collection $\\mathcal{B}\\subseteq\\mathcal{P}(X)$ is called a topological basis if $\\\\ \\textbf{1. }$ The union of its elements equals $X$. $\\\\\\textbf{2. }$ If $x \\in B_1\\cap B_2$, where $B_1,B_2\\in \\mathcal{B}$, then there exists $B_3\\subset B_1\\cap B_2$, such that $x\\in B_3$.",
                depending: []
            },
            {
                id: "3",
                content: "",
                type: "definition",
                short: "The topplogy $\\mathcal{T}$ generated by $\\mathcal{B}$ is defined as $$U\\in\\mathcal{T}\\Leftrightarrow\\forall x\\in U,\\,\\exists B\\in\\mathcal{B}: x\\in B\\subset U.$$",
                depending: []
            },
            {
                id: "1.1",
                name: "Find topology from basis",
                content: "",
                type: "theorem",
                short: "The topology generated by $\\mathcal{B}$ equals the class of all possible unions of elements in $\\mathcal{B}$.",
                depending: []
            },
            {
                id: "1.2",
                name: "Find basis from topology",
                content: "",
                type: "theorem",
                short: "The topology generated by $\\mathcal{B}$ equals the class of all possible unions of elements in $\\mathcal{B}$.",
                depending: []
            },
            {
                id: "1.2",
                name: "",
                content: "",
                type: "theorem",
                short: "Let topologies $\\mathcal{T}$ and $\\mathcal{T'}$ having bases $\\mathcal{B}$ and $\\mathcal{B}'$, respectively. Then $\\mathcal{T}\\subseteq\\mathcal{T}'$ if and only if $\\forall x\\in B\\in\\mathcal{B},\\exists B'\\in\\mathcal{B}' : x\\in B'\\subseteq B$.",
                depending: []
            },
        ]
    }
]